
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSE CONNECT ID LPAREN NUMBER OPEN PERIOD RPAREN SEND SET STRINGexpression : SET LPAREN NUMBER PERIOD NUMBER PERIOD NUMBER PERIOD NUMBER RPARENexpression : CONNECTexpression : OPENexpression : CLOSEexpression : SEND STRING'
    
_lr_action_items = {'SET':([0,],[2,]),'CONNECT':([0,],[3,]),'OPEN':([0,],[4,]),'CLOSE':([0,],[5,]),'SEND':([0,],[6,]),'$end':([1,3,4,5,8,16,],[0,-2,-3,-4,-5,-1,]),'LPAREN':([2,],[7,]),'STRING':([6,],[8,]),'NUMBER':([7,10,12,14,],[9,11,13,15,]),'PERIOD':([9,11,13,],[10,12,14,]),'RPAREN':([15,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> SET LPAREN NUMBER PERIOD NUMBER PERIOD NUMBER PERIOD NUMBER RPAREN','expression',10,'p_set','parser.py',7),
  ('expression -> CONNECT','expression',1,'p_connect','parser.py',12),
  ('expression -> OPEN','expression',1,'p_open','parser.py',17),
  ('expression -> CLOSE','expression',1,'p_close','parser.py',21),
  ('expression -> SEND STRING','expression',2,'p_send','parser.py',25),
]
